let year = 1990;
console.log(typeof year);
console.log(typeof 1991);
let name = 'Alice';
console.log(typeof name);
console.log(typeof 'Bob');
let typeOfYear = typeof year;
console.log(typeOfYear);
console.log(typeof typeOfYear);
let a = 10;
let b = 0x10;
let c = 0o10;
let d = 0b10;
let s = 'hello';
let n = s * 10;
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(n);
console.log(typeof n);
