const firstPerson = 'Maxwell Wright';
const phoneOfFirstPerson = '(0191)7196495';
const emailOfFirstPerson = 'Curabitur.egestas.nunc@nonummyac.co.uk';
const secondPerson = 'Raja Villarreal';
const phoneOfSecondPerson = '0866 398 2895';
const emailOfSecondPerson = 'posuere.vulputate@sed.com';
const thirdPerson = 'Helen Richards';
const phoneOfThirdPerson = '0800 1111';
const emailOfThirdPerson = 'libero@convallis.edu';
console.log(firstPerson,'/',phoneOfFirstPerson,'/',emailOfFirstPerson);
console.log(secondPerson,'/',phoneOfSecondPerson,'/',emailOfSecondPerson);
console.log(thirdPerson,'/',phoneOfThirdPerson,'/',emailOfThirdPerson);
